linters:
  enable-all: true
  disable:
    - godox

linters-settings:
  cyclop:
    max-complexity: 20
  depguard:
    rules:
      Main:
        list-mode: strict
        allow:
          - $gostd
          - github.com/anttikivi
          - github.com/Masterminds/semver/v3
  funlen:
    lines: 60
    statements: 40
    ignore-comments: true
  varnamelen:
    max-distance: 30
    min-name-length: 3

run:
  timeout: "1m"
