linters:
  enable-all: true
  disable:
    - godox

linters-settings:
  depguard:
    rules:
      Main:
        list-mode: strict
        allow:
          - $gostd
          - github.com/Masterminds/semver/v3
  varnamelen:
    max-distance: 20
    min-name-length: 3

run:
  timeout: "1m"
