name: Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-latest

    steps:
      - name: Fetch the source code
        uses: actions/checkout@v4.2.2

      - name: Determine the Go version
        id: go
        uses: opentofu/opentofu/.github/actions/go-version

      - name: Install the Go toolchain
        uses: actions/setup-go@v5.1.0
        with:
          go-version: ${{ steps.go.outputs.version }}

      - name: Cache the Go modules
        uses: actions/cache@v4.1.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check go.mod and go.sum
        run: |
          go mod tidy
          if [[ -n "$(git status --porcelain)" ]]; then
            echo >&2 "ERROR: go.mod/go.sum are not up-to-date. Run 'go mod tidy' and then commit the updated files."
            exit 1
          fi

      - name: Lint the code
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          version: v1.62.2

  license-check:
    name: License checks
    runs-on: ubuntu-latest

    steps:
      - name: Fetch the source code
        uses: actions/checkout@v4.2.2

      - name: Install licensei
        run: make deps

      - name: Restore the cached license information
        uses: actions/cache/restore@v4.1.2
        with:
          path: .licensei.cache
          key: ${{ runner.os }}-licensei-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-licensei-

      - name: Determine the Go version
        id: go
        uses: opentofu/opentofu/.github/actions/go-version

      - name: Install the Go toolchain
        uses: actions/setup-go@v5.1.0
        with:
          go-version: ${{ steps.go.outputs.version }}

      - name: Check the dependency licenses
        run: make license-check

      - name: Save the license information to the cache
        uses: actions/cache/save@v4.1.2
        if: always()
        with:
          path: .licensei.cache
          key: ${{ runner.os }}-licensei-${{ hashFiles('**/go.sum') }}
